### ISSUE TITLE
fastApi not opening

### ISSUE THREAD

**Issue by Syna-20** [codePerfectPlus/CorrosionAPI#2]
After running manage.py
nothing is happening
how and where do I upload the image to test?

**Comment by codeperfectplus** [comment]
It may be an installation error. I have tested it on my side and it's working.
It uses TensorFlow 1.5 version it will work with python <= 3.6.

Please create a new python 3.6 Conda environment and install requirements.txt then run 

`python manage.py`

you can visit swagger UI for testing the API:= http://localhost:8000/docs

![image](https://user-images.githubusercontent.com/54245038/213366223-ba48d6ed-5038-46b2-b85c-a8488dd6f4eb.png)

## command to create python 3.6

```bash
conda create -n tf1.5 python=3.6
conda activate tf1.5
python -m pip install -r requirements.txt
```

Please don't hesitate to let me know if you have any issues.

**Comment by Syna-20** [comment]
this I could run on python 3.7 with tf1.5 but nothing happened, as in no local server opened where I could upload the image and get the result.
![image](https://user-images.githubusercontent.com/101783446/213432865-00c99b35-90d2-481b-83ce-a6e604b37b0a.png)
  

this is the error

Then I tried creating a virtual env with python 3.6
![image](https://user-images.githubusercontent.com/101783446/213438675-e7488650-aae9-4604-937a-f6f0bf600eb2.png)
this is what I got as the outcome

**Comment by codeperfectplus** [comment]
I guess `OpenCV-python-headless` causing some issues.  try to install libraries by removing it from requirements.txt
